# ensure running in a container for fast boot, travis has these requirements:
sudo: false
dist: 'trusty'

# these are executed in order. each must pass for the next to be run
stages:
  - precache # warm up cache for default Node.js version
  - lint # lint code and docs
  - test # all tests

# defaults
language: node_js
node_js: 'node' # equivalent to stable, node 11

cache:
  yarn: true
  directories:
    - .npm
    - $HOME/.npm
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: precache
      script: true

    - stage: lint
      name: Lint contracts and frontend apps
      install: pwd # override to avoid installing modules again
      script: yarn lint

    - stage: test
      script: travis_wait 60 yarn coverage -- --scope=@tps/apps-address-book
      name: Address Book app tests and coverage report
      after_success: yarn coveralls
      env: 'COVERAGE=true'

    - stage: test
      script: travis_wait 60 yarn coverage -- --scope=@tps/apps-allocations
      name: Allocations app tests and coverage report
      after_success: yarn coveralls
      env: 'COVERAGE=true'

    - stage: test
      script: travis_wait 60 yarn coverage -- --scope=@tps/apps-projects
      name: Projects app tests and coverage report
      after_success: yarn coveralls
      env: 'COVERAGE=true'

    - stage: test
      script: travis_wait 60 yarn coverage -- --scope=@tps/apps-range-voting
      name: Range Voting app tests and coverage report
      after_success: yarn coveralls
      env: 'COVERAGE=true'

    # - &node
    #   script: yarn test
    #   node_js: 'lts/*'

notifications:
  email: false
