sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=test
  - TASK=lint
before_script:
  - npm prune
script:
- npm run $TASK